### ISSUE TITLE
Ability to click in specific Chrome tab?

### ISSUE THREAD

**Issue by woodycanuck** [versaceLORD/virtual-auto-clicker#11]
I like this tool, but I can't figure out how to specify to click in a specific Chrome tab. I have the process ID but the process name for each tab is just "chrome". Is there any way to do this?

**Comment by versaceLORD** [comment]
Hi, this is a limitation to Chrome itself. the active tab is what will be what the process is linked to. Unfortunately nothing I can add support for.
